### ISSUE TITLE
[Bug] [Windows 10] memory_hot_add_basic failed after several rerun

### ISSUE THREAD

**Issue by Tomorrow9** [vmware/ansible-vsphere-gos-validation#289]
##### SUMMARY

```
2022-05-05 08:48:21,005 | Failed at Play [memory_hot_add_basic] **********************

2022-05-05 08:48:21,005 | TASK [Execute powershell command in Windows guest] *********
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/utils/win_execute_cmd.yml:18
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py", line 600, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/action/normal.py", line 47, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py", line 1100, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py", line 1253, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/connection/psrp.py", line 465, in exec_command
    rc, stdout, stderr = self._exec_psrp_script(script, in_data)
  File "/usr/lib/python3.9/site-packages/ansible/plugins/connection/psrp.py", line 897, in _exec_psrp_script
    ps.invoke(input=input_data)
  File "/usr/lib/python3.9/site-packages/pypsrp/powershell.py", line 1218, in invoke
    return self.end_invoke()
  File "/usr/lib/python3.9/site-packages/pypsrp/powershell.py", line 1190, in end_invoke
    self.poll_invoke()
  File "/usr/lib/python3.9/site-packages/pypsrp/powershell.py", line 1391, in poll_invoke
    responses = self.runspace_pool._receive(self.id, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/pypsrp/powershell.py", line 682, in _receive
    response = self.shell.receive("stdout", command_id=command_id, timeout=timeout)[2]["stdout"]
  File "/usr/lib/python3.9/site-packages/pypsrp/shell.py", line 243, in receive
    response = self.wsman.receive(
  File "/usr/lib/python3.9/site-packages/pypsrp/wsman.py", line 367, in receive
    res = self.invoke(WSManAction.RECEIVE, resource_uri, resource, option_set, selector_set, timeout)
  File "/usr/lib/python3.9/site-packages/pypsrp/wsman.py", line 470, in invoke
    response = self.transport.send(xml)
  File "/usr/lib/python3.9/site-packages/pypsrp/wsman.py", line 837, in send
    return self._send_request(prep_request)
  File "/usr/lib/python3.9/site-packages/pypsrp/wsman.py", line 840, in _send_request
    response = self.session.send(request, timeout=(self.connection_timeout, self.read_timeout))  # type: ignore[union-attr] # This should not happen
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```
or:
```
TASK [Display the check winrm result] ******************************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:19
ok: [localhost] => {
    "check_winrm_result": {
        "changed": false,
        "elapsed": 1,
        "failed": false,
        "match_groupdict": {},
        "match_groups": [],
        "path": null,
        "port": 5986,
        "search_regex": null,
        "state": "started"
    }
}
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'

TASK [include_tasks] ***********************************************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/hotadd_memory_verify.yml:21
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
included: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/../utils/win_get_mem_size.yml for localhost
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'

TASK [include_tasks] ***********************************************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/utils/win_get_mem_size.yml:8
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
included: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/../utils/../utils/win_execute_cmd.yml for localhost
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
Read vars_file '{{ testing_vars_file | default('../../vars/test.yml') }}'
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
Using module file /root/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_shell.ps1
Pipelining is enabled.
<10.184.73.165> ESTABLISH PSRP CONNECTION FOR USER: test ON PORT 5986 TO 10.184.73.165

TASK [Execute powershell command in Windows guest] *****************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/utils/win_execute_cmd.yml:18
fatal: [localhost -> 10.184.73.165]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via PSRP: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
    "unreachable": true
}
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below



```

##### CONFIGURATION

```paste below



```

##### STEPS TO REPRODUCE

Windows 10

##### ACTUAL RESULTS

After 3 or 4 reruns, test case still failed.
```
TASK [Set fact of the memory hotadd results] ***********************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/hotadd_memory_verify.yml:40
ok: [localhost] => {
    "ansible_facts": {
        "mem_hotadd_results": [
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 2",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 2",
            "Memory hotadd succeeds: 7168->10240 with vCPU number: 2",
            "Memory hotadd succeeds: 10240->14336 with vCPU number: 2",
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 4",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 4",
            "Memory hotadd succeeds: 7168->10240 with vCPU number: 4",
            "Memory hotadd succeeds: 10240->14336 with vCPU number: 4",
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 6",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 6",
            "Memory hotadd succeeds: 7168->10240 with vCPU number: 6"
        ]
    },
    "changed": false
}
```
```
TASK [Set fact of the memory hotadd results] ***********************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/hotadd_memory_verify.yml:40
ok: [localhost] => {
    "ansible_facts": {
        "mem_hotadd_results": [
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 2",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 2",
            "Memory hotadd succeeds: 7168->10240 with vCPU number: 2",
            "Memory hotadd succeeds: 10240->14336 with vCPU number: 2",
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 4",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 4",
            "Memory hotadd succeeds: 7168->10240 with vCPU number: 4"
        ]
    },
    "changed": false
}
```
```
TASK [Set fact of the memory hotadd results] ***********************************
task path: /home/worker/workspace/Ansible_Cycle_Windows_10_64/ansible-vsphere-gos-validation/windows/memory_hot_add_basic/hotadd_memory_verify.yml:40
ok: [localhost] => {
    "ansible_facts": {
        "mem_hotadd_results": [
            "Memory hotadd succeeds: 4096->5120 with vCPU number: 2",
            "Memory hotadd succeeds: 5120->7168 with vCPU number: 2"
        ]
    },
    "changed": false
}
```

**Comment by Tomorrow9** [comment]
A workaround to decrease the failure rate is merged: https://github.com/vmware/ansible-vsphere-gos-validation/pull/320, I'll let this issue open to track the connection failure issue.

**Comment by Tomorrow9** [comment]
Rerun will resolve this issue recently, so we can close this issue.
